"error-stage1:Error communicating with OpenAI: HTTPSConnectionPool(host='chatie.deno.dev', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))"
http://sha1.sme.zscalertwo.net:10938
openai.verify_ssl_certs = False
